#!/bin/sh

sed -E -e 's/Bytes\.to_string[[:space:]]*//g' "$1" | sed -E -e 's/^(.*[[:space:]])?Bytes([^[:alpha:][:digit:]_-].*)?$/\1String\2/g' | sed -E -e 's/^(.*[[:space:]])?bytes([^[:alpha:][:digit:]_-].*)?$/\1string\2/g'
