OCAMLMAKEFILE = ../../OCamlMakefile


SOURCES = ngram.ml io.ml ngramtree.ml viterbi.ml morphtable.ml  suffix_guesser.ml  hmm_tagger.ml tagandtest.ml

LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util

RESULT = tagandtest

export OCAMLNCFLAGS := -unsafe 
#all: nc
#all: profiling-native-code
#all: profiling-byte-code
all:debug-code
include $(OCAMLMAKEFILE)

