OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = io.ml special_tokens.ml ngramtree.ml  suffix_guesser.ml train.ml

RESULT = train
LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util
PACKS=str
export OCAMLNCFLAGS := -unsafe -inline 100 
all: native-code
#all: debug-code
#all: profiling-byte-code

include $(OCAMLMAKEFILE)

