OCAMLMAKEFILE = ../../OCamlMakefile


SOURCES = ngram.ml io.ml ngramtree.ml viterbi.ml morphtable.ml  suffix_guesser.ml  hmm_tagger.ml tag.ml

LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util

RESULT = tagger

export OCAMLNCFLAGS := -unsafe 
all: nc
#all: profiling-native-code
#all: profiling-byte-code
#all:debug-code
include $(OCAMLMAKEFILE)

