OCAMLMAKEFILE = ../../OCamlMakefile


SOURCES = io.ml ngram.ml morphtable.ml special_tokens.ml lexicon.ml linear_interpolated_lm.ml ngramtree.ml  suffix_guesser.ml viterbi.ml hmm_tagger.ml tagandtest.ml

LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util
PACKS=str
RESULT = tagandtest

export OCAMLNCFLAGS := -inline 100 
#all: nc
#all: profiling-native-code
all: profiling-byte-code
#all:debug-code
include $(OCAMLMAKEFILE)

