OCAMLMAKEFILE = ../../OCamlMakefile


SOURCES = ngram.ml special_tokens.ml io.ml ngramtree.ml viterbi.ml morphtable.ml  suffix_guesser.ml  hmm_tagger.ml otnt.ml

LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util
PACKS=str
RESULT = otnt

export OCAMLNCFLAGS := -unsafe 
all: nc
#all: profiling-native-code
#all: profiling-byte-code
#all:debug-code
include $(OCAMLMAKEFILE)

