OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = io.ml  suffix_guesser.ml ngramtree.ml train.ml

RESULT = train
LIBS=ocautil
LIBDIRS=../util
INCDIRS=../util

export OCAMLNCFLAGS := -unsafe -inline 100 
all: native-code
#all: profiling-byte-code

include $(OCAMLMAKEFILE)

