OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = io.ml   ngram.ml ngramtree.ml deleted_interpolation.ml viterbi.ml morphtable.ml  tagger_hmm.ml tag.ml

RESULT = tagger


export OCAMLNCFLAGS := -unsafe 
#-inline 100 
all: profiling-native-code
#all: profiling-byte-code

include $(OCAMLMAKEFILE)

